[CONFIGURATION]
width = 15
height = 15
start = [0, 7]
goal = [14, 7]
forbidden = [[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0],[12,0],[13,0],
 [1,14],[2,14],[3,14],[4,14],[5,14],[6,14],[7,14],[8,14],[9,14],[10,14],[11,14],[12,14],[13,14],[7,1],[7,2],[7,3],[7,4],[7,5],[7,6],[7,8],[7,9],[7,10],[7,11],[7,12],[7,13]]

# i altered the config to let each algorithm show visited nodes more clearly, with more obstacles + complex pathfinding. this project was very challenging, and i learned a lot from it! thank you for a great class dr. hu